Traceback (most recent call last):
  File "/home/kishor0000/anaconda3/envs/autograde/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/kishor0000/anaconda3/envs/autograde/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/kishor0000/anaconda3/envs/autograde/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/kishor0000/anaconda3/envs/autograde/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/kishor0000/anaconda3/envs/autograde/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/kishor0000/anaconda3/envs/autograde/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/kishor0000/anaconda3/envs/autograde/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/kishor0000/anaconda3/envs/autograde/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
k = 31
error_count = 0
for i_example in range(n):

    # compute distance from the current example
    # to all other
    dist2 = np.sum((X - X[i_example])**2, axis=1)

    # find k closest examples, ignoring zero 
    # distance to the current one
    k_closest_idx = np.argsort(dist2)[1:k + 1]

    # do majority vote on the corresponding labels
    y_est = np.sign(y[k_closest_idx].sum())

    # check for errors
    if y_est * y[i_example] < 0:
        error_count += 1

print("The number of misclassified points is: ", error_count)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyboardInterrupt[0m                         Traceback (most recent call last)
Cell [0;32mIn[13], line 7[0m
[1;32m      2[0m error_count [38;5;241m=[39m [38;5;241m0[39m
[1;32m      3[0m [38;5;28;01mfor[39;00m i_example [38;5;129;01min[39;00m [38;5;28mrange[39m(n):
[1;32m      4[0m 
[1;32m      5[0m     [38;5;66;03m# compute distance from the current example[39;00m
[1;32m      6[0m     [38;5;66;03m# to all other[39;00m
[0;32m----> 7[0m     dist2 [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43msum[49m[43m([49m[43m([49m[43mX[49m[43m [49m[38;5;241;43m-[39;49m[43m [49m[43mX[49m[43m[[49m[43mi_example[49m[43m][49m[43m)[49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;241;43m2[39;49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m
[1;32m      9[0m     [38;5;66;03m# find k closest examples, ignoring zero [39;00m
[1;32m     10[0m     [38;5;66;03m# distance to the current one[39;00m
[1;32m     11[0m     k_closest_idx [38;5;241m=[39m np[38;5;241m.[39margsort(dist2)[[38;5;241m1[39m:k [38;5;241m+[39m [38;5;241m1[39m]

File [0;32m<__array_function__ internals>:177[0m, in [0;36msum[0;34m(*args, **kwargs)[0m

[0;31mKeyboardInterrupt[0m: 
KeyboardInterrupt: 

